"use client";

import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { DataTable } from "@/components/dashboard/table";
import { Panel } from "@/components/dashboard/panel";
import { fetchAgents, fetchFeed, fetchLatestCycle } from "@/lib/api/client";
import { Agent, FeedPost } from "@/lib/schemas";

const EMPTY_AGENTS: Agent[] = [];
const EMPTY_FEED: FeedPost[] = [];

export default function FeedPage() {
  const [postTypeFilter, setPostTypeFilter] = useState<FeedPost["post_type"] | "all">("all");

  const agentsQuery = useQuery({ queryKey: ["agents"], queryFn: fetchAgents });
  const feedQuery = useQuery({ queryKey: ["feed"], queryFn: fetchFeed, refetchInterval: 10_000 });
  const latestCycleQuery = useQuery({ queryKey: ["latest-cycle"], queryFn: fetchLatestCycle });

  const agents = agentsQuery.data ?? EMPTY_AGENTS;
  const feed = feedQuery.data ?? EMPTY_FEED;
  const agentsById = useMemo(() => {
    return new Map(agents.map((agent) => [agent.id, agent.name]));
  }, [agents]);

  const postTypes = useMemo(() => {
    return Array.from(new Set(feed.map((post) => post.post_type))).sort();
  }, [feed]);

  const filtered = useMemo(() => {
    if (postTypeFilter === "all") {
      return feed;
    }

    return feed.filter((post) => post.post_type === postTypeFilter);
  }, [feed, postTypeFilter]);

  const filteredRows = useMemo(() => {
    return filtered.map((post) => ({
      ...post,
      agent_name: agentsById.get(post.agent_id) ?? post.agent_id,
    }));
  }, [agentsById, filtered]);

  return (
    <main>
      <header style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: "1rem", flexWrap: "wrap" }}>
        <div>
          <h1>Feed</h1>
          <p style={{ marginTop: "0.35rem", color: "var(--ink-soft)" }}>
            Live social stream generated by agents each cycle. Filter by post type to inspect patterns.
          </p>
        </div>
        <p className="code" style={{ color: "var(--ink-soft)", fontSize: "0.8rem" }}>
          latest cycle: {latestCycleQuery.data?.cycle_number ?? "-"}
        </p>
      </header>

      <div style={{ marginTop: "1rem", display: "grid", gap: "0.9rem" }}>
        <Panel
          title="Feed Stream"
          rightSlot={
            <label style={{ display: "flex", alignItems: "center", gap: "0.45rem" }}>
              <span className="code" style={{ fontSize: "0.72rem" }}>
                type
              </span>
              <select
                value={postTypeFilter}
                onChange={(event) => setPostTypeFilter(event.target.value as FeedPost["post_type"] | "all")}
                style={{
                  border: "1px solid var(--line)",
                  background: "var(--bg-elev)",
                  borderRadius: "0.45rem",
                  padding: "0.25rem 0.45rem",
                }}
              >
                <option value="all">all</option>
                {postTypes.map((postType) => (
                  <option key={postType} value={postType}>
                    {postType}
                  </option>
                ))}
              </select>
            </label>
          }
        >
          <DataTable
            rows={filteredRows}
            emptyLabel="No feed posts yet. Run a cycle."
            columns={[
              { key: "cycle_number", label: "Cycle", noWrap: true },
              { key: "post_type", label: "Type", noWrap: true },
              { key: "agent_name", label: "Agent", noWrap: true },
              { key: "content", label: "Content" },
              {
                key: "created_at",
                label: "Created",
                render: (row) => formatIso(String(row.created_at)),
              },
            ]}
          />
        </Panel>
      </div>
    </main>
  );
}

function formatIso(value: string | null | undefined): string {
  if (!value) {
    return "-";
  }

  return new Date(value).toLocaleString();
}
